### ISSUE TITLE
[bug]Conflict with Minimal theme (and Minimal Theme Settings plugin) Image grids feature

### ISSUE THREAD

**Issue by bcdax110** [alangrainger/obsidian-image-captions#23]
- Before Minimal Image grids are turned on: works fine.
    ![Clip_2024-02-21_13-53-44](https://github.com/alangrainger/obsidian-image-captions/assets/15951421/fe6fd556-98ca-43a7-bb6e-6b2b9d5d3e42)

- After turning on Minimal Image grids: not working correctly
    ![Clip_2024-02-21_13-54-19](https://github.com/alangrainger/obsidian-image-captions/assets/15951421/916f08bd-42c4-49ae-ada2-fd1d15177d13)

**Comment by dmalaminos** [comment]
Seems to be a conflict with the line height of the figure. It's curious because I use the Minimal theme and my image grids feature is disabled, but also ran into this issue. Try using this CSS snippet:
```css
.image-captions-figure {
    line-height: normal;
}
```

**Comment by jiaochenglong** [comment]
It is recommended to update to the next version, otherwise you have to manually modify it every time you install it.

**Comment by wtrewby** [comment]
I've been having similar theme conflict issues (using Border or Minimal, but still happens with Image Grids switched off. Oddly, the text is all rendered on a single line, even with longer captions. Seems to work fine with the default theme, but I'm not sure how else to de-bug this

Border theme:
![{10B03979-7B07-4B04-9CCF-24C3D613E41A}](https://github.com/user-attachments/assets/e7393c23-f585-409b-b332-0247891cf1f0)

Default theme:
![{6FF68B59-8659-4D4C-A512-9745C5CDB3EF}](https://github.com/user-attachments/assets/ff6f0b45-afbb-47ce-a1f5-85531ce3389e)

**Comment by greetclammy** [comment]
This snipper works well for me:

![image](https://github.com/user-attachments/assets/27d19ff0-08e0-45c0-8c44-cd73021f6e69)

```css
.image-captions-figure {
 padding: 0;
 background-color: var(--bg-color) !important;
}

.image-captions-caption {
 margin: 0;
 padding-block: 5px 0;
 background-color: var(--bg-color) !important;
 color: var(--tx3);
 line-height: 1.5em;
}

.image-captions-figure { 
  margin-left: auto !important; 
  margin-right: auto!important; 
}
```
