### ISSUE TITLE
How to center the image caption?

### ISSUE THREAD

**Issue by hqgu** [alangrainger/obsidian-image-captions#3]
Is it possible to center the image caption by some CSS code?

**Comment by alangrainger** [comment]
The caption is already centered. It sounds like you have some other CSS affecting this. You can test this in the Sandbox vault and see that the captions are centered:

![image](https://user-images.githubusercontent.com/16197738/218020864-6d76cb8b-00ea-4525-ac1f-119d022a15d7.png)

If you want to center the image, use this CSS:

```css
.image-captions-figure { 
  margin-left: auto; 
  margin-right: auto; 
}
```
