### ISSUE TITLE
[Feature] Option to put the caption on top of the figure instead of at the bottom

### ISSUE THREAD

**Issue by nicolnt** [alangrainger/obsidian-image-captions#42]
By default, it is placed at the bottom like this:

![Image](https://github.com/user-attachments/assets/474f6207-85dd-4acc-99bf-a61067486e0b)

With the option set to "top" it would simply be like that:
![Image](https://github.com/user-attachments/assets/7d916d2e-b24f-491d-a146-9eb4bf60e9f2)

It would change CSS from this:
```css
.image-captions-caption {
  ...
    caption-side: bottom;
}
```

To that:
```css
.image-captions-caption {
  ...
    caption-side: top;
}
```

**Comment by alangrainger** [comment]
You can do this with a CSS snippet:

```css
.image-captions-figure {
  display: flex;
  flex-direction: column-reverse;
  width: fit-content;
}
```

<img src="https://github.com/user-attachments/assets/68d661f9-c6ba-4d03-880f-7ade084957f0" width="500">
