### ISSUE TITLE
Add an option to customize the color of the caption box or just disable the box.

### ISSUE THREAD

**Issue by MajesticStriker113** [alangrainger/obsidian-image-captions#45]
For me I use the Obsidianite theme and the grey caption box doesn't look good on the dark grey-blue background.

![image](https://github.com/user-attachments/assets/43cdd50a-9090-4035-884e-85ba800de03a)

Adding this would make this plugin be able to look a lot better with more themes.

**Comment by alangrainger** [comment]
This is exactly what [CSS snippets](https://help.obsidian.md/snippets) are for. You can change the colour to anything you wish:

```css
.image-captions-figure,
.image-captions-caption {
  background-color: yellow !important;
}
```
